applications:
  - name: libcat
    command: bundle exec rake cf:on_first_instance db:migrate && bundle exec puma -e $RAILS_ENV -p $PORT -S ~/puma -C config/puma.rb
    services:
      - libcat_db_production
    memory: 512M
    instances: 1
